apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ template "operatorNamespace" . }}
  name: istio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: istio-operator
  template:
    metadata:
      labels:
        name: istio-operator
    spec:
      serviceAccountName: istio-operator
      containers:
        - name: istio-operator
          image: {{ template "hub" . }}/operator:{{ template "tag" . }}
          command:
          - operator
          - server
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          env:
            - name: WATCH_NAMESPACE
              value: {{ template "istioNamespace" . }}
            - name: LEADER_ELECTION_NAMESPACE
              value: {{ template "operatorNamespace" . }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: {{ template "operatorNamespace" . }}
---
