apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  labels:
    chart: {{ template "bookinfo.chart" . }}
    release: {{ .Release.Name }}
    app: details
    version: v1
spec:
  replicas: {{ .Values.details.replicas }}
  selector:
    matchLabels:
      app: details
      release: {{ .Release.Name }}
      version: v1
  template:
    metadata:
      labels:
        app: details
        release: {{ .Release.Name }}
        version: v1
    spec:
      containers:
      - name: details
        image: {{.Values.hub}}/examples-bookinfo-details-v1:1.15.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.details.service.port }}