apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    app: details
    service: details
    chart: {{ template "bookinfo.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.details.service.type }}
  ports:
    - port: {{ .Values.details.service.port }}
      name: http
  selector:
    app: details
    release: {{ .Release.Name }}
