apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: reviews
    service: reviews
    chart: {{ template "bookinfo.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.reviews.service.type }}
  ports:
    - port: {{ .Values.reviews.service.port }}
      name: http
  selector:
    app: reviews
    release: {{ .Release.Name }}
