apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  labels:
    chart: {{ template "bookinfo.chart" . }}
    release: {{ .Release.Name }}
    app: reviews
    version: v2
spec:
  replicas: {{ .Values.reviews.replicas }}
  selector:
    matchLabels:
      app: reviews
      release: {{ .Release.Name }}
      version: v2
  template:
    metadata:
      labels:
        app: reviews
        release: {{ .Release.Name }}
        version: v2
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: {{.Values.hub}}/examples-bookinfo-reviews-v2:1.15.0
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: {{ .Values.reviews.service.port }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
